/*
FlowSavvy API

The FlowSavvy API is in beta and is actively evolving. While the API is in beta, breaking changes may occur without warning as we ship improvements. Please submit feedback via the in-app help center or email us at support@flowsavvy.app.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ScheduleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScheduleResponse{}

// ScheduleResponse struct for ScheduleResponse
type ScheduleResponse struct {
	ScheduleItems []ScheduleItem `json:"scheduleItems,omitempty"`
}

// NewScheduleResponse instantiates a new ScheduleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScheduleResponse() *ScheduleResponse {
	this := ScheduleResponse{}
	return &this
}

// NewScheduleResponseWithDefaults instantiates a new ScheduleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScheduleResponseWithDefaults() *ScheduleResponse {
	this := ScheduleResponse{}
	return &this
}

// GetScheduleItems returns the ScheduleItems field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScheduleResponse) GetScheduleItems() []ScheduleItem {
	if o == nil {
		var ret []ScheduleItem
		return ret
	}
	return o.ScheduleItems
}

// GetScheduleItemsOk returns a tuple with the ScheduleItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScheduleResponse) GetScheduleItemsOk() ([]ScheduleItem, bool) {
	if o == nil || IsNil(o.ScheduleItems) {
		return nil, false
	}
	return o.ScheduleItems, true
}

// HasScheduleItems returns a boolean if a field has been set.
func (o *ScheduleResponse) HasScheduleItems() bool {
	if o != nil && !IsNil(o.ScheduleItems) {
		return true
	}

	return false
}

// SetScheduleItems gets a reference to the given []ScheduleItem and assigns it to the ScheduleItems field.
func (o *ScheduleResponse) SetScheduleItems(v []ScheduleItem) {
	o.ScheduleItems = v
}

func (o ScheduleResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScheduleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ScheduleItems != nil {
		toSerialize["scheduleItems"] = o.ScheduleItems
	}
	return toSerialize, nil
}

type NullableScheduleResponse struct {
	value *ScheduleResponse
	isSet bool
}

func (v NullableScheduleResponse) Get() *ScheduleResponse {
	return v.value
}

func (v *NullableScheduleResponse) Set(val *ScheduleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduleResponse(val *ScheduleResponse) *NullableScheduleResponse {
	return &NullableScheduleResponse{value: val, isSet: true}
}

func (v NullableScheduleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
