/*
FlowSavvy API

The FlowSavvy API is in beta and is actively evolving. While the API is in beta, breaking changes may occur without warning as we ship improvements. Please submit feedback via the in-app help center or email us at support@flowsavvy.app.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ScheduleItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScheduleItem{}

// ScheduleItem Represents one rendered segment on the calendar and may be one part of a larger event or task.
type ScheduleItem struct {
	AllDay *bool `json:"allDay,omitempty"`
	// Whether the underlying item is fully completed. This differs from `thisPartCompleted`, which only refers to this specific schedule block.
	Completed *bool `json:"completed,omitempty"`
	// ISO 8601 format without offset (YYYY-MM-DDThh:mm:ss)
	EndTime *string `json:"endTime,omitempty"`
	// Indicates whether this block was generated for an auto-scheduled task.
	IsAutoScheduled *bool          `json:"isAutoScheduled,omitempty"`
	ItemId          NullableString `json:"itemId,omitempty"`
	// Indicates whether the schedule entry belongs to a `task` or an `event`.
	ItemType *string `json:"itemType,omitempty"`
	// For repeating items only. This date identifies the occurrence in a repeating series. For repeating events and fixed-time tasks, this is the date component of the occurrence's `startDateTime`. For repeating auto-scheduled tasks, this is the date component of the occurrence's `dueDateTime`.
	OccurrenceDate NullableString `json:"occurrenceDate,omitempty"`
	// ISO 8601 format without offset (YYYY-MM-DDThh:mm:ss)
	StartTime         *string        `json:"startTime,omitempty"`
	ThisPartCompleted *bool          `json:"thisPartCompleted,omitempty"`
	Title             NullableString `json:"title,omitempty"`
}

// NewScheduleItem instantiates a new ScheduleItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScheduleItem() *ScheduleItem {
	this := ScheduleItem{}
	return &this
}

// NewScheduleItemWithDefaults instantiates a new ScheduleItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScheduleItemWithDefaults() *ScheduleItem {
	this := ScheduleItem{}
	return &this
}

// GetAllDay returns the AllDay field value if set, zero value otherwise.
func (o *ScheduleItem) GetAllDay() bool {
	if o == nil || IsNil(o.AllDay) {
		var ret bool
		return ret
	}
	return *o.AllDay
}

// GetAllDayOk returns a tuple with the AllDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleItem) GetAllDayOk() (*bool, bool) {
	if o == nil || IsNil(o.AllDay) {
		return nil, false
	}
	return o.AllDay, true
}

// HasAllDay returns a boolean if a field has been set.
func (o *ScheduleItem) HasAllDay() bool {
	if o != nil && !IsNil(o.AllDay) {
		return true
	}

	return false
}

// SetAllDay gets a reference to the given bool and assigns it to the AllDay field.
func (o *ScheduleItem) SetAllDay(v bool) {
	o.AllDay = &v
}

// GetCompleted returns the Completed field value if set, zero value otherwise.
func (o *ScheduleItem) GetCompleted() bool {
	if o == nil || IsNil(o.Completed) {
		var ret bool
		return ret
	}
	return *o.Completed
}

// GetCompletedOk returns a tuple with the Completed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleItem) GetCompletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Completed) {
		return nil, false
	}
	return o.Completed, true
}

// HasCompleted returns a boolean if a field has been set.
func (o *ScheduleItem) HasCompleted() bool {
	if o != nil && !IsNil(o.Completed) {
		return true
	}

	return false
}

// SetCompleted gets a reference to the given bool and assigns it to the Completed field.
func (o *ScheduleItem) SetCompleted(v bool) {
	o.Completed = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *ScheduleItem) GetEndTime() string {
	if o == nil || IsNil(o.EndTime) {
		var ret string
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleItem) GetEndTimeOk() (*string, bool) {
	if o == nil || IsNil(o.EndTime) {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *ScheduleItem) HasEndTime() bool {
	if o != nil && !IsNil(o.EndTime) {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given string and assigns it to the EndTime field.
func (o *ScheduleItem) SetEndTime(v string) {
	o.EndTime = &v
}

// GetIsAutoScheduled returns the IsAutoScheduled field value if set, zero value otherwise.
func (o *ScheduleItem) GetIsAutoScheduled() bool {
	if o == nil || IsNil(o.IsAutoScheduled) {
		var ret bool
		return ret
	}
	return *o.IsAutoScheduled
}

// GetIsAutoScheduledOk returns a tuple with the IsAutoScheduled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleItem) GetIsAutoScheduledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAutoScheduled) {
		return nil, false
	}
	return o.IsAutoScheduled, true
}

// HasIsAutoScheduled returns a boolean if a field has been set.
func (o *ScheduleItem) HasIsAutoScheduled() bool {
	if o != nil && !IsNil(o.IsAutoScheduled) {
		return true
	}

	return false
}

// SetIsAutoScheduled gets a reference to the given bool and assigns it to the IsAutoScheduled field.
func (o *ScheduleItem) SetIsAutoScheduled(v bool) {
	o.IsAutoScheduled = &v
}

// GetItemId returns the ItemId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScheduleItem) GetItemId() string {
	if o == nil || IsNil(o.ItemId.Get()) {
		var ret string
		return ret
	}
	return *o.ItemId.Get()
}

// GetItemIdOk returns a tuple with the ItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScheduleItem) GetItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemId.Get(), o.ItemId.IsSet()
}

// HasItemId returns a boolean if a field has been set.
func (o *ScheduleItem) HasItemId() bool {
	if o != nil && o.ItemId.IsSet() {
		return true
	}

	return false
}

// SetItemId gets a reference to the given NullableString and assigns it to the ItemId field.
func (o *ScheduleItem) SetItemId(v string) {
	o.ItemId.Set(&v)
}

// SetItemIdNil sets the value for ItemId to be an explicit nil
func (o *ScheduleItem) SetItemIdNil() {
	o.ItemId.Set(nil)
}

// UnsetItemId ensures that no value is present for ItemId, not even an explicit nil
func (o *ScheduleItem) UnsetItemId() {
	o.ItemId.Unset()
}

// GetItemType returns the ItemType field value if set, zero value otherwise.
func (o *ScheduleItem) GetItemType() string {
	if o == nil || IsNil(o.ItemType) {
		var ret string
		return ret
	}
	return *o.ItemType
}

// GetItemTypeOk returns a tuple with the ItemType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleItem) GetItemTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ItemType) {
		return nil, false
	}
	return o.ItemType, true
}

// HasItemType returns a boolean if a field has been set.
func (o *ScheduleItem) HasItemType() bool {
	if o != nil && !IsNil(o.ItemType) {
		return true
	}

	return false
}

// SetItemType gets a reference to the given string and assigns it to the ItemType field.
func (o *ScheduleItem) SetItemType(v string) {
	o.ItemType = &v
}

// GetOccurrenceDate returns the OccurrenceDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScheduleItem) GetOccurrenceDate() string {
	if o == nil || IsNil(o.OccurrenceDate.Get()) {
		var ret string
		return ret
	}
	return *o.OccurrenceDate.Get()
}

// GetOccurrenceDateOk returns a tuple with the OccurrenceDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScheduleItem) GetOccurrenceDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OccurrenceDate.Get(), o.OccurrenceDate.IsSet()
}

// HasOccurrenceDate returns a boolean if a field has been set.
func (o *ScheduleItem) HasOccurrenceDate() bool {
	if o != nil && o.OccurrenceDate.IsSet() {
		return true
	}

	return false
}

// SetOccurrenceDate gets a reference to the given NullableString and assigns it to the OccurrenceDate field.
func (o *ScheduleItem) SetOccurrenceDate(v string) {
	o.OccurrenceDate.Set(&v)
}

// SetOccurrenceDateNil sets the value for OccurrenceDate to be an explicit nil
func (o *ScheduleItem) SetOccurrenceDateNil() {
	o.OccurrenceDate.Set(nil)
}

// UnsetOccurrenceDate ensures that no value is present for OccurrenceDate, not even an explicit nil
func (o *ScheduleItem) UnsetOccurrenceDate() {
	o.OccurrenceDate.Unset()
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *ScheduleItem) GetStartTime() string {
	if o == nil || IsNil(o.StartTime) {
		var ret string
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleItem) GetStartTimeOk() (*string, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *ScheduleItem) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given string and assigns it to the StartTime field.
func (o *ScheduleItem) SetStartTime(v string) {
	o.StartTime = &v
}

// GetThisPartCompleted returns the ThisPartCompleted field value if set, zero value otherwise.
func (o *ScheduleItem) GetThisPartCompleted() bool {
	if o == nil || IsNil(o.ThisPartCompleted) {
		var ret bool
		return ret
	}
	return *o.ThisPartCompleted
}

// GetThisPartCompletedOk returns a tuple with the ThisPartCompleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleItem) GetThisPartCompletedOk() (*bool, bool) {
	if o == nil || IsNil(o.ThisPartCompleted) {
		return nil, false
	}
	return o.ThisPartCompleted, true
}

// HasThisPartCompleted returns a boolean if a field has been set.
func (o *ScheduleItem) HasThisPartCompleted() bool {
	if o != nil && !IsNil(o.ThisPartCompleted) {
		return true
	}

	return false
}

// SetThisPartCompleted gets a reference to the given bool and assigns it to the ThisPartCompleted field.
func (o *ScheduleItem) SetThisPartCompleted(v bool) {
	o.ThisPartCompleted = &v
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScheduleItem) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScheduleItem) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *ScheduleItem) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *ScheduleItem) SetTitle(v string) {
	o.Title.Set(&v)
}

// SetTitleNil sets the value for Title to be an explicit nil
func (o *ScheduleItem) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *ScheduleItem) UnsetTitle() {
	o.Title.Unset()
}

func (o ScheduleItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScheduleItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllDay) {
		toSerialize["allDay"] = o.AllDay
	}
	if !IsNil(o.Completed) {
		toSerialize["completed"] = o.Completed
	}
	if !IsNil(o.EndTime) {
		toSerialize["endTime"] = o.EndTime
	}
	if !IsNil(o.IsAutoScheduled) {
		toSerialize["isAutoScheduled"] = o.IsAutoScheduled
	}
	if o.ItemId.IsSet() {
		toSerialize["itemId"] = o.ItemId.Get()
	}
	if !IsNil(o.ItemType) {
		toSerialize["itemType"] = o.ItemType
	}
	if o.OccurrenceDate.IsSet() {
		toSerialize["occurrenceDate"] = o.OccurrenceDate.Get()
	}
	if !IsNil(o.StartTime) {
		toSerialize["startTime"] = o.StartTime
	}
	if !IsNil(o.ThisPartCompleted) {
		toSerialize["thisPartCompleted"] = o.ThisPartCompleted
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	return toSerialize, nil
}

type NullableScheduleItem struct {
	value *ScheduleItem
	isSet bool
}

func (v NullableScheduleItem) Get() *ScheduleItem {
	return v.value
}

func (v *NullableScheduleItem) Set(val *ScheduleItem) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduleItem) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduleItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduleItem(val *ScheduleItem) *NullableScheduleItem {
	return &NullableScheduleItem{value: val, isSet: true}
}

func (v NullableScheduleItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduleItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
