/*
FlowSavvy API

The FlowSavvy API is in beta and is actively evolving. While the API is in beta, breaking changes may occur without warning as we ship improvements. Please submit feedback via the in-app help center or email us at support@flowsavvy.app.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the Item type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Item{}

// Item struct for Item
type Item struct {
	// Discriminator for item subtype. Can be `task` or `event`.
	ItemType string `json:"itemType"`
	// Buffer after this item in minutes. Defaults to the value set in event and task settings.
	BufferAfterMinutes NullableInt32 `json:"bufferAfterMinutes,omitempty"`
	// Buffer before this item in minutes. Defaults to the value set in event and task settings.
	BufferBeforeMinutes NullableInt32 `json:"bufferBeforeMinutes,omitempty"`
	// For repeating items only, dates where an occurrence was deleted.
	CancelledOccurrenceDates []string `json:"cancelledOccurrenceDates,omitempty"`
	// Event/task display color override in hex format (e.g. \"#FF0000\"). Null means \"use calendar/list/default color behavior.\"
	CustomColor NullableString `json:"customColor,omitempty"`
	// ISO 8601 format in UTC (YYYY-MM-DDThh:mm:ssZ)
	DateCreated *string        `json:"dateCreated,omitempty"`
	Id          NullableString `json:"id,omitempty"`
	// ISO 8601 format in UTC (YYYY-MM-DDThh:mm:ssZ)
	LastModified *string `json:"lastModified,omitempty"`
	// Rich-text HTML string. Typical tags include paragraphs, inline formatting, lists, and links. Examples: `<p>Call Alex</p>`, `<p><strong>Important:</strong> bring docs</p>`, `<ul><li>First</li><li>Second</li></ul>`. Truncated to 8192 chars during validation.
	Notes NullableString `json:"notes,omitempty"`
	// When this item is an edited occurrence of a repeating series, this date identifies where the occurrence was originally in the repeating series. For repeating events and fixed-time tasks, this is the date component of the occurrence's original `startDateTime`. For repeating auto-scheduled tasks, this is the date component of the occurrence's original `dueDateTime`.
	OccurrenceDate NullableString `json:"occurrenceDate,omitempty"`
	// Points to the ID of this item's parent when this item is an edited occurrence of a recurring item. If null, this item is not an edited occurrence and represents the main/original item.
	ParentItemId NullableString `json:"parentItemId,omitempty"`
	// RRULE string without the `RRULE:` prefix (e.g. FREQ=DAILY;INTERVAL=1). Null means non-repeating.
	RecurrenceRule NullableString `json:"recurrenceRule,omitempty"`
	// Can be an IANA time zone id or `Floating`, which follows the user's time zone when it changes. Set to null to apply the user's \"time zone default\" setting.
	TimeZone NullableString `json:"timeZone,omitempty"`
	Title    NullableString `json:"title,omitempty"`
}

type _Item Item

// NewItem instantiates a new Item object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItem(itemType string) *Item {
	this := Item{}
	this.ItemType = itemType
	return &this
}

// NewItemWithDefaults instantiates a new Item object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemWithDefaults() *Item {
	this := Item{}
	return &this
}

// GetItemType returns the ItemType field value
func (o *Item) GetItemType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ItemType
}

// GetItemTypeOk returns a tuple with the ItemType field value
// and a boolean to check if the value has been set.
func (o *Item) GetItemTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ItemType, true
}

// SetItemType sets field value
func (o *Item) SetItemType(v string) {
	o.ItemType = v
}

// GetBufferAfterMinutes returns the BufferAfterMinutes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Item) GetBufferAfterMinutes() int32 {
	if o == nil || IsNil(o.BufferAfterMinutes.Get()) {
		var ret int32
		return ret
	}
	return *o.BufferAfterMinutes.Get()
}

// GetBufferAfterMinutesOk returns a tuple with the BufferAfterMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Item) GetBufferAfterMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BufferAfterMinutes.Get(), o.BufferAfterMinutes.IsSet()
}

// HasBufferAfterMinutes returns a boolean if a field has been set.
func (o *Item) HasBufferAfterMinutes() bool {
	if o != nil && o.BufferAfterMinutes.IsSet() {
		return true
	}

	return false
}

// SetBufferAfterMinutes gets a reference to the given NullableInt32 and assigns it to the BufferAfterMinutes field.
func (o *Item) SetBufferAfterMinutes(v int32) {
	o.BufferAfterMinutes.Set(&v)
}

// SetBufferAfterMinutesNil sets the value for BufferAfterMinutes to be an explicit nil
func (o *Item) SetBufferAfterMinutesNil() {
	o.BufferAfterMinutes.Set(nil)
}

// UnsetBufferAfterMinutes ensures that no value is present for BufferAfterMinutes, not even an explicit nil
func (o *Item) UnsetBufferAfterMinutes() {
	o.BufferAfterMinutes.Unset()
}

// GetBufferBeforeMinutes returns the BufferBeforeMinutes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Item) GetBufferBeforeMinutes() int32 {
	if o == nil || IsNil(o.BufferBeforeMinutes.Get()) {
		var ret int32
		return ret
	}
	return *o.BufferBeforeMinutes.Get()
}

// GetBufferBeforeMinutesOk returns a tuple with the BufferBeforeMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Item) GetBufferBeforeMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BufferBeforeMinutes.Get(), o.BufferBeforeMinutes.IsSet()
}

// HasBufferBeforeMinutes returns a boolean if a field has been set.
func (o *Item) HasBufferBeforeMinutes() bool {
	if o != nil && o.BufferBeforeMinutes.IsSet() {
		return true
	}

	return false
}

// SetBufferBeforeMinutes gets a reference to the given NullableInt32 and assigns it to the BufferBeforeMinutes field.
func (o *Item) SetBufferBeforeMinutes(v int32) {
	o.BufferBeforeMinutes.Set(&v)
}

// SetBufferBeforeMinutesNil sets the value for BufferBeforeMinutes to be an explicit nil
func (o *Item) SetBufferBeforeMinutesNil() {
	o.BufferBeforeMinutes.Set(nil)
}

// UnsetBufferBeforeMinutes ensures that no value is present for BufferBeforeMinutes, not even an explicit nil
func (o *Item) UnsetBufferBeforeMinutes() {
	o.BufferBeforeMinutes.Unset()
}

// GetCancelledOccurrenceDates returns the CancelledOccurrenceDates field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Item) GetCancelledOccurrenceDates() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.CancelledOccurrenceDates
}

// GetCancelledOccurrenceDatesOk returns a tuple with the CancelledOccurrenceDates field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Item) GetCancelledOccurrenceDatesOk() ([]string, bool) {
	if o == nil || IsNil(o.CancelledOccurrenceDates) {
		return nil, false
	}
	return o.CancelledOccurrenceDates, true
}

// HasCancelledOccurrenceDates returns a boolean if a field has been set.
func (o *Item) HasCancelledOccurrenceDates() bool {
	if o != nil && !IsNil(o.CancelledOccurrenceDates) {
		return true
	}

	return false
}

// SetCancelledOccurrenceDates gets a reference to the given []string and assigns it to the CancelledOccurrenceDates field.
func (o *Item) SetCancelledOccurrenceDates(v []string) {
	o.CancelledOccurrenceDates = v
}

// GetCustomColor returns the CustomColor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Item) GetCustomColor() string {
	if o == nil || IsNil(o.CustomColor.Get()) {
		var ret string
		return ret
	}
	return *o.CustomColor.Get()
}

// GetCustomColorOk returns a tuple with the CustomColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Item) GetCustomColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomColor.Get(), o.CustomColor.IsSet()
}

// HasCustomColor returns a boolean if a field has been set.
func (o *Item) HasCustomColor() bool {
	if o != nil && o.CustomColor.IsSet() {
		return true
	}

	return false
}

// SetCustomColor gets a reference to the given NullableString and assigns it to the CustomColor field.
func (o *Item) SetCustomColor(v string) {
	o.CustomColor.Set(&v)
}

// SetCustomColorNil sets the value for CustomColor to be an explicit nil
func (o *Item) SetCustomColorNil() {
	o.CustomColor.Set(nil)
}

// UnsetCustomColor ensures that no value is present for CustomColor, not even an explicit nil
func (o *Item) UnsetCustomColor() {
	o.CustomColor.Unset()
}

// GetDateCreated returns the DateCreated field value if set, zero value otherwise.
func (o *Item) GetDateCreated() string {
	if o == nil || IsNil(o.DateCreated) {
		var ret string
		return ret
	}
	return *o.DateCreated
}

// GetDateCreatedOk returns a tuple with the DateCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetDateCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.DateCreated) {
		return nil, false
	}
	return o.DateCreated, true
}

// HasDateCreated returns a boolean if a field has been set.
func (o *Item) HasDateCreated() bool {
	if o != nil && !IsNil(o.DateCreated) {
		return true
	}

	return false
}

// SetDateCreated gets a reference to the given string and assigns it to the DateCreated field.
func (o *Item) SetDateCreated(v string) {
	o.DateCreated = &v
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Item) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Item) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *Item) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *Item) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *Item) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *Item) UnsetId() {
	o.Id.Unset()
}

// GetLastModified returns the LastModified field value if set, zero value otherwise.
func (o *Item) GetLastModified() string {
	if o == nil || IsNil(o.LastModified) {
		var ret string
		return ret
	}
	return *o.LastModified
}

// GetLastModifiedOk returns a tuple with the LastModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetLastModifiedOk() (*string, bool) {
	if o == nil || IsNil(o.LastModified) {
		return nil, false
	}
	return o.LastModified, true
}

// HasLastModified returns a boolean if a field has been set.
func (o *Item) HasLastModified() bool {
	if o != nil && !IsNil(o.LastModified) {
		return true
	}

	return false
}

// SetLastModified gets a reference to the given string and assigns it to the LastModified field.
func (o *Item) SetLastModified(v string) {
	o.LastModified = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Item) GetNotes() string {
	if o == nil || IsNil(o.Notes.Get()) {
		var ret string
		return ret
	}
	return *o.Notes.Get()
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Item) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notes.Get(), o.Notes.IsSet()
}

// HasNotes returns a boolean if a field has been set.
func (o *Item) HasNotes() bool {
	if o != nil && o.Notes.IsSet() {
		return true
	}

	return false
}

// SetNotes gets a reference to the given NullableString and assigns it to the Notes field.
func (o *Item) SetNotes(v string) {
	o.Notes.Set(&v)
}

// SetNotesNil sets the value for Notes to be an explicit nil
func (o *Item) SetNotesNil() {
	o.Notes.Set(nil)
}

// UnsetNotes ensures that no value is present for Notes, not even an explicit nil
func (o *Item) UnsetNotes() {
	o.Notes.Unset()
}

// GetOccurrenceDate returns the OccurrenceDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Item) GetOccurrenceDate() string {
	if o == nil || IsNil(o.OccurrenceDate.Get()) {
		var ret string
		return ret
	}
	return *o.OccurrenceDate.Get()
}

// GetOccurrenceDateOk returns a tuple with the OccurrenceDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Item) GetOccurrenceDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OccurrenceDate.Get(), o.OccurrenceDate.IsSet()
}

// HasOccurrenceDate returns a boolean if a field has been set.
func (o *Item) HasOccurrenceDate() bool {
	if o != nil && o.OccurrenceDate.IsSet() {
		return true
	}

	return false
}

// SetOccurrenceDate gets a reference to the given NullableString and assigns it to the OccurrenceDate field.
func (o *Item) SetOccurrenceDate(v string) {
	o.OccurrenceDate.Set(&v)
}

// SetOccurrenceDateNil sets the value for OccurrenceDate to be an explicit nil
func (o *Item) SetOccurrenceDateNil() {
	o.OccurrenceDate.Set(nil)
}

// UnsetOccurrenceDate ensures that no value is present for OccurrenceDate, not even an explicit nil
func (o *Item) UnsetOccurrenceDate() {
	o.OccurrenceDate.Unset()
}

// GetParentItemId returns the ParentItemId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Item) GetParentItemId() string {
	if o == nil || IsNil(o.ParentItemId.Get()) {
		var ret string
		return ret
	}
	return *o.ParentItemId.Get()
}

// GetParentItemIdOk returns a tuple with the ParentItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Item) GetParentItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentItemId.Get(), o.ParentItemId.IsSet()
}

// HasParentItemId returns a boolean if a field has been set.
func (o *Item) HasParentItemId() bool {
	if o != nil && o.ParentItemId.IsSet() {
		return true
	}

	return false
}

// SetParentItemId gets a reference to the given NullableString and assigns it to the ParentItemId field.
func (o *Item) SetParentItemId(v string) {
	o.ParentItemId.Set(&v)
}

// SetParentItemIdNil sets the value for ParentItemId to be an explicit nil
func (o *Item) SetParentItemIdNil() {
	o.ParentItemId.Set(nil)
}

// UnsetParentItemId ensures that no value is present for ParentItemId, not even an explicit nil
func (o *Item) UnsetParentItemId() {
	o.ParentItemId.Unset()
}

// GetRecurrenceRule returns the RecurrenceRule field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Item) GetRecurrenceRule() string {
	if o == nil || IsNil(o.RecurrenceRule.Get()) {
		var ret string
		return ret
	}
	return *o.RecurrenceRule.Get()
}

// GetRecurrenceRuleOk returns a tuple with the RecurrenceRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Item) GetRecurrenceRuleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecurrenceRule.Get(), o.RecurrenceRule.IsSet()
}

// HasRecurrenceRule returns a boolean if a field has been set.
func (o *Item) HasRecurrenceRule() bool {
	if o != nil && o.RecurrenceRule.IsSet() {
		return true
	}

	return false
}

// SetRecurrenceRule gets a reference to the given NullableString and assigns it to the RecurrenceRule field.
func (o *Item) SetRecurrenceRule(v string) {
	o.RecurrenceRule.Set(&v)
}

// SetRecurrenceRuleNil sets the value for RecurrenceRule to be an explicit nil
func (o *Item) SetRecurrenceRuleNil() {
	o.RecurrenceRule.Set(nil)
}

// UnsetRecurrenceRule ensures that no value is present for RecurrenceRule, not even an explicit nil
func (o *Item) UnsetRecurrenceRule() {
	o.RecurrenceRule.Unset()
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Item) GetTimeZone() string {
	if o == nil || IsNil(o.TimeZone.Get()) {
		var ret string
		return ret
	}
	return *o.TimeZone.Get()
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Item) GetTimeZoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimeZone.Get(), o.TimeZone.IsSet()
}

// HasTimeZone returns a boolean if a field has been set.
func (o *Item) HasTimeZone() bool {
	if o != nil && o.TimeZone.IsSet() {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given NullableString and assigns it to the TimeZone field.
func (o *Item) SetTimeZone(v string) {
	o.TimeZone.Set(&v)
}

// SetTimeZoneNil sets the value for TimeZone to be an explicit nil
func (o *Item) SetTimeZoneNil() {
	o.TimeZone.Set(nil)
}

// UnsetTimeZone ensures that no value is present for TimeZone, not even an explicit nil
func (o *Item) UnsetTimeZone() {
	o.TimeZone.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Item) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Item) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *Item) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *Item) SetTitle(v string) {
	o.Title.Set(&v)
}

// SetTitleNil sets the value for Title to be an explicit nil
func (o *Item) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *Item) UnsetTitle() {
	o.Title.Unset()
}

func (o Item) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Item) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["itemType"] = o.ItemType
	if o.BufferAfterMinutes.IsSet() {
		toSerialize["bufferAfterMinutes"] = o.BufferAfterMinutes.Get()
	}
	if o.BufferBeforeMinutes.IsSet() {
		toSerialize["bufferBeforeMinutes"] = o.BufferBeforeMinutes.Get()
	}
	if o.CancelledOccurrenceDates != nil {
		toSerialize["cancelledOccurrenceDates"] = o.CancelledOccurrenceDates
	}
	if o.CustomColor.IsSet() {
		toSerialize["customColor"] = o.CustomColor.Get()
	}
	if !IsNil(o.DateCreated) {
		toSerialize["dateCreated"] = o.DateCreated
	}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if !IsNil(o.LastModified) {
		toSerialize["lastModified"] = o.LastModified
	}
	if o.Notes.IsSet() {
		toSerialize["notes"] = o.Notes.Get()
	}
	if o.OccurrenceDate.IsSet() {
		toSerialize["occurrenceDate"] = o.OccurrenceDate.Get()
	}
	if o.ParentItemId.IsSet() {
		toSerialize["parentItemId"] = o.ParentItemId.Get()
	}
	if o.RecurrenceRule.IsSet() {
		toSerialize["recurrenceRule"] = o.RecurrenceRule.Get()
	}
	if o.TimeZone.IsSet() {
		toSerialize["timeZone"] = o.TimeZone.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	return toSerialize, nil
}

type NullableItem struct {
	value *Item
	isSet bool
}

func (v NullableItem) Get() *Item {
	return v.value
}

func (v *NullableItem) Set(val *Item) {
	v.value = val
	v.isSet = true
}

func (v NullableItem) IsSet() bool {
	return v.isSet
}

func (v *NullableItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItem(val *Item) *NullableItem {
	return &NullableItem{value: val, isSet: true}
}

func (v NullableItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
