/*
FlowSavvy API

The FlowSavvy API is in beta and is actively evolving. While the API is in beta, breaking changes may occur without warning as we ship improvements. Please submit feedback via the in-app help center or email us at support@flowsavvy.app.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Event type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Event{}

// Event struct for Event
type Event struct {
	Item
	AllDay *bool `json:"allDay,omitempty"`
	// Indicates busy/free availability. Defaults to `false` for all-day events and `true` for regular events.
	Busy NullableBool `json:"busy,omitempty"`
	// The id of the calendar this event belongs to. Omit to set to the user's default calendar.
	CalendarId NullableString `json:"calendarId,omitempty"`
	// End of the event. This date/time is exclusive, so for all-day events, this is  12am on the day after the last day of the event. For example, an all-day event  on May 10 would have an endDateTime of May 11 at 12am. ISO 8601 format without offset (YYYY-MM-DDThh:mm:ss)
	EndDateTime string         `json:"endDateTime"`
	Location    NullableString `json:"location,omitempty"`
	// Start of the event. For all-day events, always uses midnight. ISO 8601 format without offset (YYYY-MM-DDThh:mm:ss)
	StartDateTime string `json:"startDateTime"`
}

type _Event Event

// NewEvent instantiates a new Event object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvent(endDateTime string, startDateTime string, itemType string) *Event {
	this := Event{}
	this.ItemType = itemType
	this.EndDateTime = endDateTime
	this.StartDateTime = startDateTime
	return &this
}

// NewEventWithDefaults instantiates a new Event object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventWithDefaults() *Event {
	this := Event{}
	return &this
}

// GetAllDay returns the AllDay field value if set, zero value otherwise.
func (o *Event) GetAllDay() bool {
	if o == nil || IsNil(o.AllDay) {
		var ret bool
		return ret
	}
	return *o.AllDay
}

// GetAllDayOk returns a tuple with the AllDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetAllDayOk() (*bool, bool) {
	if o == nil || IsNil(o.AllDay) {
		return nil, false
	}
	return o.AllDay, true
}

// HasAllDay returns a boolean if a field has been set.
func (o *Event) HasAllDay() bool {
	if o != nil && !IsNil(o.AllDay) {
		return true
	}

	return false
}

// SetAllDay gets a reference to the given bool and assigns it to the AllDay field.
func (o *Event) SetAllDay(v bool) {
	o.AllDay = &v
}

// GetBusy returns the Busy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetBusy() bool {
	if o == nil || IsNil(o.Busy.Get()) {
		var ret bool
		return ret
	}
	return *o.Busy.Get()
}

// GetBusyOk returns a tuple with the Busy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetBusyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Busy.Get(), o.Busy.IsSet()
}

// HasBusy returns a boolean if a field has been set.
func (o *Event) HasBusy() bool {
	if o != nil && o.Busy.IsSet() {
		return true
	}

	return false
}

// SetBusy gets a reference to the given NullableBool and assigns it to the Busy field.
func (o *Event) SetBusy(v bool) {
	o.Busy.Set(&v)
}

// SetBusyNil sets the value for Busy to be an explicit nil
func (o *Event) SetBusyNil() {
	o.Busy.Set(nil)
}

// UnsetBusy ensures that no value is present for Busy, not even an explicit nil
func (o *Event) UnsetBusy() {
	o.Busy.Unset()
}

// GetCalendarId returns the CalendarId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetCalendarId() string {
	if o == nil || IsNil(o.CalendarId.Get()) {
		var ret string
		return ret
	}
	return *o.CalendarId.Get()
}

// GetCalendarIdOk returns a tuple with the CalendarId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetCalendarIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CalendarId.Get(), o.CalendarId.IsSet()
}

// HasCalendarId returns a boolean if a field has been set.
func (o *Event) HasCalendarId() bool {
	if o != nil && o.CalendarId.IsSet() {
		return true
	}

	return false
}

// SetCalendarId gets a reference to the given NullableString and assigns it to the CalendarId field.
func (o *Event) SetCalendarId(v string) {
	o.CalendarId.Set(&v)
}

// SetCalendarIdNil sets the value for CalendarId to be an explicit nil
func (o *Event) SetCalendarIdNil() {
	o.CalendarId.Set(nil)
}

// UnsetCalendarId ensures that no value is present for CalendarId, not even an explicit nil
func (o *Event) UnsetCalendarId() {
	o.CalendarId.Unset()
}

// GetEndDateTime returns the EndDateTime field value
func (o *Event) GetEndDateTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndDateTime
}

// GetEndDateTimeOk returns a tuple with the EndDateTime field value
// and a boolean to check if the value has been set.
func (o *Event) GetEndDateTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndDateTime, true
}

// SetEndDateTime sets field value
func (o *Event) SetEndDateTime(v string) {
	o.EndDateTime = v
}

// GetLocation returns the Location field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetLocation() string {
	if o == nil || IsNil(o.Location.Get()) {
		var ret string
		return ret
	}
	return *o.Location.Get()
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Location.Get(), o.Location.IsSet()
}

// HasLocation returns a boolean if a field has been set.
func (o *Event) HasLocation() bool {
	if o != nil && o.Location.IsSet() {
		return true
	}

	return false
}

// SetLocation gets a reference to the given NullableString and assigns it to the Location field.
func (o *Event) SetLocation(v string) {
	o.Location.Set(&v)
}

// SetLocationNil sets the value for Location to be an explicit nil
func (o *Event) SetLocationNil() {
	o.Location.Set(nil)
}

// UnsetLocation ensures that no value is present for Location, not even an explicit nil
func (o *Event) UnsetLocation() {
	o.Location.Unset()
}

// GetStartDateTime returns the StartDateTime field value
func (o *Event) GetStartDateTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartDateTime
}

// GetStartDateTimeOk returns a tuple with the StartDateTime field value
// and a boolean to check if the value has been set.
func (o *Event) GetStartDateTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartDateTime, true
}

// SetStartDateTime sets field value
func (o *Event) SetStartDateTime(v string) {
	o.StartDateTime = v
}

func (o Event) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Event) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedItem, errItem := json.Marshal(o.Item)
	if errItem != nil {
		return map[string]interface{}{}, errItem
	}
	errItem = json.Unmarshal([]byte(serializedItem), &toSerialize)
	if errItem != nil {
		return map[string]interface{}{}, errItem
	}
	if !IsNil(o.AllDay) {
		toSerialize["allDay"] = o.AllDay
	}
	if o.Busy.IsSet() {
		toSerialize["busy"] = o.Busy.Get()
	}
	if o.CalendarId.IsSet() {
		toSerialize["calendarId"] = o.CalendarId.Get()
	}
	toSerialize["endDateTime"] = o.EndDateTime
	if o.Location.IsSet() {
		toSerialize["location"] = o.Location.Get()
	}
	toSerialize["startDateTime"] = o.StartDateTime
	return toSerialize, nil
}

func (o *Event) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endDateTime",
		"startDateTime",
		"itemType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEvent := _Event{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEvent)

	if err != nil {
		return err
	}

	*o = Event(varEvent)

	return err
}

type NullableEvent struct {
	value *Event
	isSet bool
}

func (v NullableEvent) Get() *Event {
	return v.value
}

func (v *NullableEvent) Set(val *Event) {
	v.value = val
	v.isSet = true
}

func (v NullableEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvent(val *Event) *NullableEvent {
	return &NullableEvent{value: val, isSet: true}
}

func (v NullableEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
