/*
FlowSavvy API

The FlowSavvy API is in beta and is actively evolving. While the API is in beta, breaking changes may occur without warning as we ship improvements. Please submit feedback via the in-app help center or email us at support@flowsavvy.app.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ItemsListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ItemsListResponse{}

// ItemsListResponse struct for ItemsListResponse
type ItemsListResponse struct {
	Items []GetItem200Response `json:"items,omitempty"`
	// Token used to access the next page of this result. Omitted if no further results are available.
	NextPageToken NullableString `json:"nextPageToken,omitempty"`
}

// NewItemsListResponse instantiates a new ItemsListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemsListResponse() *ItemsListResponse {
	this := ItemsListResponse{}
	return &this
}

// NewItemsListResponseWithDefaults instantiates a new ItemsListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemsListResponseWithDefaults() *ItemsListResponse {
	this := ItemsListResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemsListResponse) GetItems() []GetItem200Response {
	if o == nil {
		var ret []GetItem200Response
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemsListResponse) GetItemsOk() ([]GetItem200Response, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ItemsListResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []GetItem200Response and assigns it to the Items field.
func (o *ItemsListResponse) SetItems(v []GetItem200Response) {
	o.Items = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemsListResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken.Get()) {
		var ret string
		return ret
	}
	return *o.NextPageToken.Get()
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemsListResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextPageToken.Get(), o.NextPageToken.IsSet()
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ItemsListResponse) HasNextPageToken() bool {
	if o != nil && o.NextPageToken.IsSet() {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given NullableString and assigns it to the NextPageToken field.
func (o *ItemsListResponse) SetNextPageToken(v string) {
	o.NextPageToken.Set(&v)
}

// SetNextPageTokenNil sets the value for NextPageToken to be an explicit nil
func (o *ItemsListResponse) SetNextPageTokenNil() {
	o.NextPageToken.Set(nil)
}

// UnsetNextPageToken ensures that no value is present for NextPageToken, not even an explicit nil
func (o *ItemsListResponse) UnsetNextPageToken() {
	o.NextPageToken.Unset()
}

func (o ItemsListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ItemsListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.NextPageToken.IsSet() {
		toSerialize["nextPageToken"] = o.NextPageToken.Get()
	}
	return toSerialize, nil
}

type NullableItemsListResponse struct {
	value *ItemsListResponse
	isSet bool
}

func (v NullableItemsListResponse) Get() *ItemsListResponse {
	return v.value
}

func (v *NullableItemsListResponse) Set(val *ItemsListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableItemsListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableItemsListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemsListResponse(val *ItemsListResponse) *NullableItemsListResponse {
	return &NullableItemsListResponse{value: val, isSet: true}
}

func (v NullableItemsListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemsListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
