/*
FlowSavvy API

The FlowSavvy API is in beta and is actively evolving. While the API is in beta, breaking changes may occur without warning as we ship improvements. Please submit feedback via the in-app help center or email us at support@flowsavvy.app.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the SchedulingHours type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchedulingHours{}

// SchedulingHours struct for SchedulingHours
type SchedulingHours struct {
	Id    NullableString `json:"id,omitempty"`
	Title NullableString `json:"title,omitempty"`
	// Recurring weekly availability keyed by weekday (`sunday` … `saturday`).
	RecurringHours *map[string][]TimeRange `json:"recurringHours,omitempty"`
	// Date-specific overrides keyed by calendar date (YYYY-MM-DD). Dates not listed use `recurringHours`. An empty array means that date is explicitly blocked.
	DateOverrides *map[string][]TimeRange `json:"dateOverrides,omitempty"`
}

// NewSchedulingHours instantiates a new SchedulingHours object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchedulingHours() *SchedulingHours {
	this := SchedulingHours{}
	return &this
}

// NewSchedulingHoursWithDefaults instantiates a new SchedulingHours object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchedulingHoursWithDefaults() *SchedulingHours {
	this := SchedulingHours{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SchedulingHours) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SchedulingHours) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *SchedulingHours) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *SchedulingHours) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *SchedulingHours) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *SchedulingHours) UnsetId() {
	o.Id.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SchedulingHours) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SchedulingHours) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *SchedulingHours) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *SchedulingHours) SetTitle(v string) {
	o.Title.Set(&v)
}

// SetTitleNil sets the value for Title to be an explicit nil
func (o *SchedulingHours) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *SchedulingHours) UnsetTitle() {
	o.Title.Unset()
}

// GetRecurringHours returns the RecurringHours field value if set, zero value otherwise.
func (o *SchedulingHours) GetRecurringHours() map[string][]TimeRange {
	if o == nil || IsNil(o.RecurringHours) {
		var ret map[string][]TimeRange
		return ret
	}
	return *o.RecurringHours
}

// GetRecurringHoursOk returns a tuple with the RecurringHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchedulingHours) GetRecurringHoursOk() (*map[string][]TimeRange, bool) {
	if o == nil || IsNil(o.RecurringHours) {
		return nil, false
	}
	return o.RecurringHours, true
}

// HasRecurringHours returns a boolean if a field has been set.
func (o *SchedulingHours) HasRecurringHours() bool {
	if o != nil && !IsNil(o.RecurringHours) {
		return true
	}

	return false
}

// SetRecurringHours gets a reference to the given map[string][]TimeRange and assigns it to the RecurringHours field.
func (o *SchedulingHours) SetRecurringHours(v map[string][]TimeRange) {
	o.RecurringHours = &v
}

// GetDateOverrides returns the DateOverrides field value if set, zero value otherwise.
func (o *SchedulingHours) GetDateOverrides() map[string][]TimeRange {
	if o == nil || IsNil(o.DateOverrides) {
		var ret map[string][]TimeRange
		return ret
	}
	return *o.DateOverrides
}

// GetDateOverridesOk returns a tuple with the DateOverrides field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchedulingHours) GetDateOverridesOk() (*map[string][]TimeRange, bool) {
	if o == nil || IsNil(o.DateOverrides) {
		return nil, false
	}
	return o.DateOverrides, true
}

// HasDateOverrides returns a boolean if a field has been set.
func (o *SchedulingHours) HasDateOverrides() bool {
	if o != nil && !IsNil(o.DateOverrides) {
		return true
	}

	return false
}

// SetDateOverrides gets a reference to the given map[string][]TimeRange and assigns it to the DateOverrides field.
func (o *SchedulingHours) SetDateOverrides(v map[string][]TimeRange) {
	o.DateOverrides = &v
}

func (o SchedulingHours) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchedulingHours) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if !IsNil(o.RecurringHours) {
		toSerialize["recurringHours"] = o.RecurringHours
	}
	if !IsNil(o.DateOverrides) {
		toSerialize["dateOverrides"] = o.DateOverrides
	}
	return toSerialize, nil
}

type NullableSchedulingHours struct {
	value *SchedulingHours
	isSet bool
}

func (v NullableSchedulingHours) Get() *SchedulingHours {
	return v.value
}

func (v *NullableSchedulingHours) Set(val *SchedulingHours) {
	v.value = val
	v.isSet = true
}

func (v NullableSchedulingHours) IsSet() bool {
	return v.isSet
}

func (v *NullableSchedulingHours) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchedulingHours(val *SchedulingHours) *NullableSchedulingHours {
	return &NullableSchedulingHours{value: val, isSet: true}
}

func (v NullableSchedulingHours) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchedulingHours) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
