/*
FlowSavvy API

The FlowSavvy API is in beta and is actively evolving. While the API is in beta, breaking changes may occur without warning as we ship improvements. Please submit feedback via the in-app help center or email us at support@flowsavvy.app.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the CalendarsListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalendarsListResponse{}

// CalendarsListResponse struct for CalendarsListResponse
type CalendarsListResponse struct {
	Calendars []Calendar `json:"calendars,omitempty"`
	// The user's default calendar id.
	DefaultCalendarId NullableString `json:"defaultCalendarId,omitempty"`
}

// NewCalendarsListResponse instantiates a new CalendarsListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalendarsListResponse() *CalendarsListResponse {
	this := CalendarsListResponse{}
	return &this
}

// NewCalendarsListResponseWithDefaults instantiates a new CalendarsListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalendarsListResponseWithDefaults() *CalendarsListResponse {
	this := CalendarsListResponse{}
	return &this
}

// GetCalendars returns the Calendars field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CalendarsListResponse) GetCalendars() []Calendar {
	if o == nil {
		var ret []Calendar
		return ret
	}
	return o.Calendars
}

// GetCalendarsOk returns a tuple with the Calendars field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CalendarsListResponse) GetCalendarsOk() ([]Calendar, bool) {
	if o == nil || IsNil(o.Calendars) {
		return nil, false
	}
	return o.Calendars, true
}

// HasCalendars returns a boolean if a field has been set.
func (o *CalendarsListResponse) HasCalendars() bool {
	if o != nil && !IsNil(o.Calendars) {
		return true
	}

	return false
}

// SetCalendars gets a reference to the given []Calendar and assigns it to the Calendars field.
func (o *CalendarsListResponse) SetCalendars(v []Calendar) {
	o.Calendars = v
}

// GetDefaultCalendarId returns the DefaultCalendarId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CalendarsListResponse) GetDefaultCalendarId() string {
	if o == nil || IsNil(o.DefaultCalendarId.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultCalendarId.Get()
}

// GetDefaultCalendarIdOk returns a tuple with the DefaultCalendarId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CalendarsListResponse) GetDefaultCalendarIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultCalendarId.Get(), o.DefaultCalendarId.IsSet()
}

// HasDefaultCalendarId returns a boolean if a field has been set.
func (o *CalendarsListResponse) HasDefaultCalendarId() bool {
	if o != nil && o.DefaultCalendarId.IsSet() {
		return true
	}

	return false
}

// SetDefaultCalendarId gets a reference to the given NullableString and assigns it to the DefaultCalendarId field.
func (o *CalendarsListResponse) SetDefaultCalendarId(v string) {
	o.DefaultCalendarId.Set(&v)
}

// SetDefaultCalendarIdNil sets the value for DefaultCalendarId to be an explicit nil
func (o *CalendarsListResponse) SetDefaultCalendarIdNil() {
	o.DefaultCalendarId.Set(nil)
}

// UnsetDefaultCalendarId ensures that no value is present for DefaultCalendarId, not even an explicit nil
func (o *CalendarsListResponse) UnsetDefaultCalendarId() {
	o.DefaultCalendarId.Unset()
}

func (o CalendarsListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalendarsListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Calendars != nil {
		toSerialize["calendars"] = o.Calendars
	}
	if o.DefaultCalendarId.IsSet() {
		toSerialize["defaultCalendarId"] = o.DefaultCalendarId.Get()
	}
	return toSerialize, nil
}

type NullableCalendarsListResponse struct {
	value *CalendarsListResponse
	isSet bool
}

func (v NullableCalendarsListResponse) Get() *CalendarsListResponse {
	return v.value
}

func (v *NullableCalendarsListResponse) Set(val *CalendarsListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCalendarsListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCalendarsListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalendarsListResponse(val *CalendarsListResponse) *NullableCalendarsListResponse {
	return &NullableCalendarsListResponse{value: val, isSet: true}
}

func (v NullableCalendarsListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalendarsListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
