/*
FlowSavvy API

The FlowSavvy API is in beta and is actively evolving. While the API is in beta, breaking changes may occur without warning as we ship improvements. Please submit feedback via the in-app help center or email us at support@flowsavvy.app.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ListsListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListsListResponse{}

// ListsListResponse struct for ListsListResponse
type ListsListResponse struct {
	// The user's default task list id, or `null` for the inbox.
	DefaultListId NullableString `json:"defaultListId,omitempty"`
	Lists         []List         `json:"lists,omitempty"`
}

// NewListsListResponse instantiates a new ListsListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListsListResponse() *ListsListResponse {
	this := ListsListResponse{}
	return &this
}

// NewListsListResponseWithDefaults instantiates a new ListsListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListsListResponseWithDefaults() *ListsListResponse {
	this := ListsListResponse{}
	return &this
}

// GetDefaultListId returns the DefaultListId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListsListResponse) GetDefaultListId() string {
	if o == nil || IsNil(o.DefaultListId.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultListId.Get()
}

// GetDefaultListIdOk returns a tuple with the DefaultListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListsListResponse) GetDefaultListIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultListId.Get(), o.DefaultListId.IsSet()
}

// HasDefaultListId returns a boolean if a field has been set.
func (o *ListsListResponse) HasDefaultListId() bool {
	if o != nil && o.DefaultListId.IsSet() {
		return true
	}

	return false
}

// SetDefaultListId gets a reference to the given NullableString and assigns it to the DefaultListId field.
func (o *ListsListResponse) SetDefaultListId(v string) {
	o.DefaultListId.Set(&v)
}

// SetDefaultListIdNil sets the value for DefaultListId to be an explicit nil
func (o *ListsListResponse) SetDefaultListIdNil() {
	o.DefaultListId.Set(nil)
}

// UnsetDefaultListId ensures that no value is present for DefaultListId, not even an explicit nil
func (o *ListsListResponse) UnsetDefaultListId() {
	o.DefaultListId.Unset()
}

// GetLists returns the Lists field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListsListResponse) GetLists() []List {
	if o == nil {
		var ret []List
		return ret
	}
	return o.Lists
}

// GetListsOk returns a tuple with the Lists field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListsListResponse) GetListsOk() ([]List, bool) {
	if o == nil || IsNil(o.Lists) {
		return nil, false
	}
	return o.Lists, true
}

// HasLists returns a boolean if a field has been set.
func (o *ListsListResponse) HasLists() bool {
	if o != nil && !IsNil(o.Lists) {
		return true
	}

	return false
}

// SetLists gets a reference to the given []List and assigns it to the Lists field.
func (o *ListsListResponse) SetLists(v []List) {
	o.Lists = v
}

func (o ListsListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListsListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DefaultListId.IsSet() {
		toSerialize["defaultListId"] = o.DefaultListId.Get()
	}
	if o.Lists != nil {
		toSerialize["lists"] = o.Lists
	}
	return toSerialize, nil
}

type NullableListsListResponse struct {
	value *ListsListResponse
	isSet bool
}

func (v NullableListsListResponse) Get() *ListsListResponse {
	return v.value
}

func (v *NullableListsListResponse) Set(val *ListsListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListsListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListsListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListsListResponse(val *ListsListResponse) *NullableListsListResponse {
	return &NullableListsListResponse{value: val, isSet: true}
}

func (v NullableListsListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListsListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
