/*
FlowSavvy API

The FlowSavvy API is in beta and is actively evolving. While the API is in beta, breaking changes may occur without warning as we ship improvements. Please submit feedback via the in-app help center or email us at support@flowsavvy.app.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the SchedulingHoursListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchedulingHoursListResponse{}

// SchedulingHoursListResponse struct for SchedulingHoursListResponse
type SchedulingHoursListResponse struct {
	// The user's default scheduling hours id.
	DefaultSchedulingHoursId NullableString    `json:"defaultSchedulingHoursId,omitempty"`
	SchedulingHours          []SchedulingHours `json:"schedulingHours,omitempty"`
}

// NewSchedulingHoursListResponse instantiates a new SchedulingHoursListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchedulingHoursListResponse() *SchedulingHoursListResponse {
	this := SchedulingHoursListResponse{}
	return &this
}

// NewSchedulingHoursListResponseWithDefaults instantiates a new SchedulingHoursListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchedulingHoursListResponseWithDefaults() *SchedulingHoursListResponse {
	this := SchedulingHoursListResponse{}
	return &this
}

// GetDefaultSchedulingHoursId returns the DefaultSchedulingHoursId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SchedulingHoursListResponse) GetDefaultSchedulingHoursId() string {
	if o == nil || IsNil(o.DefaultSchedulingHoursId.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultSchedulingHoursId.Get()
}

// GetDefaultSchedulingHoursIdOk returns a tuple with the DefaultSchedulingHoursId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SchedulingHoursListResponse) GetDefaultSchedulingHoursIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultSchedulingHoursId.Get(), o.DefaultSchedulingHoursId.IsSet()
}

// HasDefaultSchedulingHoursId returns a boolean if a field has been set.
func (o *SchedulingHoursListResponse) HasDefaultSchedulingHoursId() bool {
	if o != nil && o.DefaultSchedulingHoursId.IsSet() {
		return true
	}

	return false
}

// SetDefaultSchedulingHoursId gets a reference to the given NullableString and assigns it to the DefaultSchedulingHoursId field.
func (o *SchedulingHoursListResponse) SetDefaultSchedulingHoursId(v string) {
	o.DefaultSchedulingHoursId.Set(&v)
}

// SetDefaultSchedulingHoursIdNil sets the value for DefaultSchedulingHoursId to be an explicit nil
func (o *SchedulingHoursListResponse) SetDefaultSchedulingHoursIdNil() {
	o.DefaultSchedulingHoursId.Set(nil)
}

// UnsetDefaultSchedulingHoursId ensures that no value is present for DefaultSchedulingHoursId, not even an explicit nil
func (o *SchedulingHoursListResponse) UnsetDefaultSchedulingHoursId() {
	o.DefaultSchedulingHoursId.Unset()
}

// GetSchedulingHours returns the SchedulingHours field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SchedulingHoursListResponse) GetSchedulingHours() []SchedulingHours {
	if o == nil {
		var ret []SchedulingHours
		return ret
	}
	return o.SchedulingHours
}

// GetSchedulingHoursOk returns a tuple with the SchedulingHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SchedulingHoursListResponse) GetSchedulingHoursOk() ([]SchedulingHours, bool) {
	if o == nil || IsNil(o.SchedulingHours) {
		return nil, false
	}
	return o.SchedulingHours, true
}

// HasSchedulingHours returns a boolean if a field has been set.
func (o *SchedulingHoursListResponse) HasSchedulingHours() bool {
	if o != nil && !IsNil(o.SchedulingHours) {
		return true
	}

	return false
}

// SetSchedulingHours gets a reference to the given []SchedulingHours and assigns it to the SchedulingHours field.
func (o *SchedulingHoursListResponse) SetSchedulingHours(v []SchedulingHours) {
	o.SchedulingHours = v
}

func (o SchedulingHoursListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchedulingHoursListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DefaultSchedulingHoursId.IsSet() {
		toSerialize["defaultSchedulingHoursId"] = o.DefaultSchedulingHoursId.Get()
	}
	if o.SchedulingHours != nil {
		toSerialize["schedulingHours"] = o.SchedulingHours
	}
	return toSerialize, nil
}

type NullableSchedulingHoursListResponse struct {
	value *SchedulingHoursListResponse
	isSet bool
}

func (v NullableSchedulingHoursListResponse) Get() *SchedulingHoursListResponse {
	return v.value
}

func (v *NullableSchedulingHoursListResponse) Set(val *SchedulingHoursListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSchedulingHoursListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSchedulingHoursListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchedulingHoursListResponse(val *SchedulingHoursListResponse) *NullableSchedulingHoursListResponse {
	return &NullableSchedulingHoursListResponse{value: val, isSet: true}
}

func (v NullableSchedulingHoursListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchedulingHoursListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
