/*
FlowSavvy API

The FlowSavvy API is in beta and is actively evolving. While the API is in beta, breaking changes may occur without warning as we ship improvements. Please submit feedback via the in-app help center or email us at support@flowsavvy.app.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// GetItem200Response - struct for GetItem200Response
type GetItem200Response struct {
	Event *Event
	Task  *Task
}

// EventAsGetItem200Response is a convenience function that returns Event wrapped in GetItem200Response
func EventAsGetItem200Response(v *Event) GetItem200Response {
	return GetItem200Response{
		Event: v,
	}
}

// TaskAsGetItem200Response is a convenience function that returns Task wrapped in GetItem200Response
func TaskAsGetItem200Response(v *Task) GetItem200Response {
	return GetItem200Response{
		Task: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetItem200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Event
	err = newStrictDecoder(data).Decode(&dst.Event)
	if err == nil {
		jsonEvent, _ := json.Marshal(dst.Event)
		if string(jsonEvent) == "{}" { // empty struct
			dst.Event = nil
		} else {
			if err = validator.Validate(dst.Event); err != nil {
				dst.Event = nil
			} else {
				match++
			}
		}
	} else {
		dst.Event = nil
	}

	// try to unmarshal data into Task
	err = newStrictDecoder(data).Decode(&dst.Task)
	if err == nil {
		jsonTask, _ := json.Marshal(dst.Task)
		if string(jsonTask) == "{}" { // empty struct
			dst.Task = nil
		} else {
			if err = validator.Validate(dst.Task); err != nil {
				dst.Task = nil
			} else {
				match++
			}
		}
	} else {
		dst.Task = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Event = nil
		dst.Task = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetItem200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetItem200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetItem200Response) MarshalJSON() ([]byte, error) {
	if src.Event != nil {
		return json.Marshal(&src.Event)
	}

	if src.Task != nil {
		return json.Marshal(&src.Task)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetItem200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.Event != nil {
		return obj.Event
	}

	if obj.Task != nil {
		return obj.Task
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj GetItem200Response) GetActualInstanceValue() interface{} {
	if obj.Event != nil {
		return *obj.Event
	}

	if obj.Task != nil {
		return *obj.Task
	}

	// all schemas are nil
	return nil
}

type NullableGetItem200Response struct {
	value *GetItem200Response
	isSet bool
}

func (v NullableGetItem200Response) Get() *GetItem200Response {
	return v.value
}

func (v *NullableGetItem200Response) Set(val *GetItem200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetItem200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetItem200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetItem200Response(val *GetItem200Response) *NullableGetItem200Response {
	return &NullableGetItem200Response{value: val, isSet: true}
}

func (v NullableGetItem200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetItem200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
