/*
FlowSavvy API

The FlowSavvy API is in beta and is actively evolving. While the API is in beta, breaking changes may occur without warning as we ship improvements. Please submit feedback via the in-app help center or email us at support@flowsavvy.app.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Task type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Task{}

// Task struct for Task
type Task struct {
	Item
	// IDs of items that this task must be scheduled after.
	BlockedByIds []string `json:"blockedByIds,omitempty"`
	// IDs of items that this task must be scheduled before.
	BlocksIds []string `json:"blocksIds,omitempty"`
	// Only applies to auto-scheduled tasks. Indicates when work can begin. For non-repeating tasks, null means \"can be started now\". For repeating tasks, the time span between `canBeStartedAt` and `dueDateTime` defines how early each occurrence can be started before its due date. ISO 8601 format without offset (YYYY-MM-DDThh:mm:ss)
	CanBeStartedAt NullableString `json:"canBeStartedAt,omitempty"`
	Completed      *bool          `json:"completed,omitempty"`
	// The date/time the task should be scheduled before. Required for repeating auto-scheduled tasks since the due date is what repeats. ISO 8601 format without offset (YYYY-MM-DDThh:mm:ss)
	DueDateTime NullableString `json:"dueDateTime,omitempty"`
	// Only applies to auto-scheduled tasks. Tasks must be less than 24 hours long.
	DurationMinutes NullableInt32 `json:"durationMinutes,omitempty"`
	// Only applies to fixed-time tasks. Tasks must be less than 24 hours long. ISO 8601 format without offset (YYYY-MM-DDThh:mm:ss)
	EndDateTime NullableString `json:"endDateTime,omitempty"`
	// When a task can't be scheduled before its deadline: if `true`, the task is ignored;  if `false`, it is scheduled after the deadline. Defaults to `true` for repeating tasks and `false` for non-repeating tasks.
	IsAutoIgnored NullableBool `json:"isAutoIgnored,omitempty"`
	// When `true`, FlowSavvy auto-schedules the task based on duration, due date, scheduling hours, and more. When `false`, the task is a <i>fixed-time task</i> pinned to a specific time using `startDateTime` and `endDateTime` instead. Tasks in the inbox (`listId` is `inbox`) are never scheduled. When omitted, presence of `startDateTime` implies fixed-time, and absence of `startDateTime` implies auto-scheduled.
	IsAutoScheduled NullableBool `json:"isAutoScheduled,omitempty"`
	// The ID of the task list this task belongs to. `inbox` means the task is in the inbox.  Tasks in the inbox do not get scheduled. Omit to set to the user's default list.
	ListId NullableString `json:"listId,omitempty"`
	// Minimum length in minutes of any scheduled chunk of this task. Only applies to auto-scheduled tasks. Set to the full duration to disable splitting. When omitted, this value gets set using the values for \"Splittable\" and \"Min duration\" in \"Events and tasks\" settings and the task's duration.
	MinLengthMinutes NullableInt32 `json:"minLengthMinutes,omitempty"`
	// Omitted or null defaults to `normal`.
	Priority NullableString `json:"priority,omitempty"`
	// Completed progress in minutes. Ignored when creating a task.
	ProgressMinutes NullableInt32 `json:"progressMinutes,omitempty"`
	// The id of the scheduling hours during which this task can be scheduled. Only applies to auto-scheduled tasks. Omit to set to the list's default scheduling hours.
	SchedulingHoursId NullableString `json:"schedulingHoursId,omitempty"`
	// Only applies to fixed-time tasks. ISO 8601 format without offset (YYYY-MM-DDThh:mm:ss)
	StartDateTime NullableString `json:"startDateTime,omitempty"`
}

type _Task Task

// NewTask instantiates a new Task object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTask(itemType string) *Task {
	this := Task{}
	this.ItemType = itemType
	return &this
}

// NewTaskWithDefaults instantiates a new Task object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskWithDefaults() *Task {
	this := Task{}
	return &this
}

// GetBlockedByIds returns the BlockedByIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Task) GetBlockedByIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.BlockedByIds
}

// GetBlockedByIdsOk returns a tuple with the BlockedByIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Task) GetBlockedByIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.BlockedByIds) {
		return nil, false
	}
	return o.BlockedByIds, true
}

// HasBlockedByIds returns a boolean if a field has been set.
func (o *Task) HasBlockedByIds() bool {
	if o != nil && !IsNil(o.BlockedByIds) {
		return true
	}

	return false
}

// SetBlockedByIds gets a reference to the given []string and assigns it to the BlockedByIds field.
func (o *Task) SetBlockedByIds(v []string) {
	o.BlockedByIds = v
}

// GetBlocksIds returns the BlocksIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Task) GetBlocksIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.BlocksIds
}

// GetBlocksIdsOk returns a tuple with the BlocksIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Task) GetBlocksIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.BlocksIds) {
		return nil, false
	}
	return o.BlocksIds, true
}

// HasBlocksIds returns a boolean if a field has been set.
func (o *Task) HasBlocksIds() bool {
	if o != nil && !IsNil(o.BlocksIds) {
		return true
	}

	return false
}

// SetBlocksIds gets a reference to the given []string and assigns it to the BlocksIds field.
func (o *Task) SetBlocksIds(v []string) {
	o.BlocksIds = v
}

// GetCanBeStartedAt returns the CanBeStartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Task) GetCanBeStartedAt() string {
	if o == nil || IsNil(o.CanBeStartedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CanBeStartedAt.Get()
}

// GetCanBeStartedAtOk returns a tuple with the CanBeStartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Task) GetCanBeStartedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CanBeStartedAt.Get(), o.CanBeStartedAt.IsSet()
}

// HasCanBeStartedAt returns a boolean if a field has been set.
func (o *Task) HasCanBeStartedAt() bool {
	if o != nil && o.CanBeStartedAt.IsSet() {
		return true
	}

	return false
}

// SetCanBeStartedAt gets a reference to the given NullableString and assigns it to the CanBeStartedAt field.
func (o *Task) SetCanBeStartedAt(v string) {
	o.CanBeStartedAt.Set(&v)
}

// SetCanBeStartedAtNil sets the value for CanBeStartedAt to be an explicit nil
func (o *Task) SetCanBeStartedAtNil() {
	o.CanBeStartedAt.Set(nil)
}

// UnsetCanBeStartedAt ensures that no value is present for CanBeStartedAt, not even an explicit nil
func (o *Task) UnsetCanBeStartedAt() {
	o.CanBeStartedAt.Unset()
}

// GetCompleted returns the Completed field value if set, zero value otherwise.
func (o *Task) GetCompleted() bool {
	if o == nil || IsNil(o.Completed) {
		var ret bool
		return ret
	}
	return *o.Completed
}

// GetCompletedOk returns a tuple with the Completed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Task) GetCompletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Completed) {
		return nil, false
	}
	return o.Completed, true
}

// HasCompleted returns a boolean if a field has been set.
func (o *Task) HasCompleted() bool {
	if o != nil && !IsNil(o.Completed) {
		return true
	}

	return false
}

// SetCompleted gets a reference to the given bool and assigns it to the Completed field.
func (o *Task) SetCompleted(v bool) {
	o.Completed = &v
}

// GetDueDateTime returns the DueDateTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Task) GetDueDateTime() string {
	if o == nil || IsNil(o.DueDateTime.Get()) {
		var ret string
		return ret
	}
	return *o.DueDateTime.Get()
}

// GetDueDateTimeOk returns a tuple with the DueDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Task) GetDueDateTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DueDateTime.Get(), o.DueDateTime.IsSet()
}

// HasDueDateTime returns a boolean if a field has been set.
func (o *Task) HasDueDateTime() bool {
	if o != nil && o.DueDateTime.IsSet() {
		return true
	}

	return false
}

// SetDueDateTime gets a reference to the given NullableString and assigns it to the DueDateTime field.
func (o *Task) SetDueDateTime(v string) {
	o.DueDateTime.Set(&v)
}

// SetDueDateTimeNil sets the value for DueDateTime to be an explicit nil
func (o *Task) SetDueDateTimeNil() {
	o.DueDateTime.Set(nil)
}

// UnsetDueDateTime ensures that no value is present for DueDateTime, not even an explicit nil
func (o *Task) UnsetDueDateTime() {
	o.DueDateTime.Unset()
}

// GetDurationMinutes returns the DurationMinutes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Task) GetDurationMinutes() int32 {
	if o == nil || IsNil(o.DurationMinutes.Get()) {
		var ret int32
		return ret
	}
	return *o.DurationMinutes.Get()
}

// GetDurationMinutesOk returns a tuple with the DurationMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Task) GetDurationMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DurationMinutes.Get(), o.DurationMinutes.IsSet()
}

// HasDurationMinutes returns a boolean if a field has been set.
func (o *Task) HasDurationMinutes() bool {
	if o != nil && o.DurationMinutes.IsSet() {
		return true
	}

	return false
}

// SetDurationMinutes gets a reference to the given NullableInt32 and assigns it to the DurationMinutes field.
func (o *Task) SetDurationMinutes(v int32) {
	o.DurationMinutes.Set(&v)
}

// SetDurationMinutesNil sets the value for DurationMinutes to be an explicit nil
func (o *Task) SetDurationMinutesNil() {
	o.DurationMinutes.Set(nil)
}

// UnsetDurationMinutes ensures that no value is present for DurationMinutes, not even an explicit nil
func (o *Task) UnsetDurationMinutes() {
	o.DurationMinutes.Unset()
}

// GetEndDateTime returns the EndDateTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Task) GetEndDateTime() string {
	if o == nil || IsNil(o.EndDateTime.Get()) {
		var ret string
		return ret
	}
	return *o.EndDateTime.Get()
}

// GetEndDateTimeOk returns a tuple with the EndDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Task) GetEndDateTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDateTime.Get(), o.EndDateTime.IsSet()
}

// HasEndDateTime returns a boolean if a field has been set.
func (o *Task) HasEndDateTime() bool {
	if o != nil && o.EndDateTime.IsSet() {
		return true
	}

	return false
}

// SetEndDateTime gets a reference to the given NullableString and assigns it to the EndDateTime field.
func (o *Task) SetEndDateTime(v string) {
	o.EndDateTime.Set(&v)
}

// SetEndDateTimeNil sets the value for EndDateTime to be an explicit nil
func (o *Task) SetEndDateTimeNil() {
	o.EndDateTime.Set(nil)
}

// UnsetEndDateTime ensures that no value is present for EndDateTime, not even an explicit nil
func (o *Task) UnsetEndDateTime() {
	o.EndDateTime.Unset()
}

// GetIsAutoIgnored returns the IsAutoIgnored field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Task) GetIsAutoIgnored() bool {
	if o == nil || IsNil(o.IsAutoIgnored.Get()) {
		var ret bool
		return ret
	}
	return *o.IsAutoIgnored.Get()
}

// GetIsAutoIgnoredOk returns a tuple with the IsAutoIgnored field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Task) GetIsAutoIgnoredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsAutoIgnored.Get(), o.IsAutoIgnored.IsSet()
}

// HasIsAutoIgnored returns a boolean if a field has been set.
func (o *Task) HasIsAutoIgnored() bool {
	if o != nil && o.IsAutoIgnored.IsSet() {
		return true
	}

	return false
}

// SetIsAutoIgnored gets a reference to the given NullableBool and assigns it to the IsAutoIgnored field.
func (o *Task) SetIsAutoIgnored(v bool) {
	o.IsAutoIgnored.Set(&v)
}

// SetIsAutoIgnoredNil sets the value for IsAutoIgnored to be an explicit nil
func (o *Task) SetIsAutoIgnoredNil() {
	o.IsAutoIgnored.Set(nil)
}

// UnsetIsAutoIgnored ensures that no value is present for IsAutoIgnored, not even an explicit nil
func (o *Task) UnsetIsAutoIgnored() {
	o.IsAutoIgnored.Unset()
}

// GetIsAutoScheduled returns the IsAutoScheduled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Task) GetIsAutoScheduled() bool {
	if o == nil || IsNil(o.IsAutoScheduled.Get()) {
		var ret bool
		return ret
	}
	return *o.IsAutoScheduled.Get()
}

// GetIsAutoScheduledOk returns a tuple with the IsAutoScheduled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Task) GetIsAutoScheduledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsAutoScheduled.Get(), o.IsAutoScheduled.IsSet()
}

// HasIsAutoScheduled returns a boolean if a field has been set.
func (o *Task) HasIsAutoScheduled() bool {
	if o != nil && o.IsAutoScheduled.IsSet() {
		return true
	}

	return false
}

// SetIsAutoScheduled gets a reference to the given NullableBool and assigns it to the IsAutoScheduled field.
func (o *Task) SetIsAutoScheduled(v bool) {
	o.IsAutoScheduled.Set(&v)
}

// SetIsAutoScheduledNil sets the value for IsAutoScheduled to be an explicit nil
func (o *Task) SetIsAutoScheduledNil() {
	o.IsAutoScheduled.Set(nil)
}

// UnsetIsAutoScheduled ensures that no value is present for IsAutoScheduled, not even an explicit nil
func (o *Task) UnsetIsAutoScheduled() {
	o.IsAutoScheduled.Unset()
}

// GetListId returns the ListId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Task) GetListId() string {
	if o == nil || IsNil(o.ListId.Get()) {
		var ret string
		return ret
	}
	return *o.ListId.Get()
}

// GetListIdOk returns a tuple with the ListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Task) GetListIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ListId.Get(), o.ListId.IsSet()
}

// HasListId returns a boolean if a field has been set.
func (o *Task) HasListId() bool {
	if o != nil && o.ListId.IsSet() {
		return true
	}

	return false
}

// SetListId gets a reference to the given NullableString and assigns it to the ListId field.
func (o *Task) SetListId(v string) {
	o.ListId.Set(&v)
}

// SetListIdNil sets the value for ListId to be an explicit nil
func (o *Task) SetListIdNil() {
	o.ListId.Set(nil)
}

// UnsetListId ensures that no value is present for ListId, not even an explicit nil
func (o *Task) UnsetListId() {
	o.ListId.Unset()
}

// GetMinLengthMinutes returns the MinLengthMinutes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Task) GetMinLengthMinutes() int32 {
	if o == nil || IsNil(o.MinLengthMinutes.Get()) {
		var ret int32
		return ret
	}
	return *o.MinLengthMinutes.Get()
}

// GetMinLengthMinutesOk returns a tuple with the MinLengthMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Task) GetMinLengthMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MinLengthMinutes.Get(), o.MinLengthMinutes.IsSet()
}

// HasMinLengthMinutes returns a boolean if a field has been set.
func (o *Task) HasMinLengthMinutes() bool {
	if o != nil && o.MinLengthMinutes.IsSet() {
		return true
	}

	return false
}

// SetMinLengthMinutes gets a reference to the given NullableInt32 and assigns it to the MinLengthMinutes field.
func (o *Task) SetMinLengthMinutes(v int32) {
	o.MinLengthMinutes.Set(&v)
}

// SetMinLengthMinutesNil sets the value for MinLengthMinutes to be an explicit nil
func (o *Task) SetMinLengthMinutesNil() {
	o.MinLengthMinutes.Set(nil)
}

// UnsetMinLengthMinutes ensures that no value is present for MinLengthMinutes, not even an explicit nil
func (o *Task) UnsetMinLengthMinutes() {
	o.MinLengthMinutes.Unset()
}

// GetPriority returns the Priority field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Task) GetPriority() string {
	if o == nil || IsNil(o.Priority.Get()) {
		var ret string
		return ret
	}
	return *o.Priority.Get()
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Task) GetPriorityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Priority.Get(), o.Priority.IsSet()
}

// HasPriority returns a boolean if a field has been set.
func (o *Task) HasPriority() bool {
	if o != nil && o.Priority.IsSet() {
		return true
	}

	return false
}

// SetPriority gets a reference to the given NullableString and assigns it to the Priority field.
func (o *Task) SetPriority(v string) {
	o.Priority.Set(&v)
}

// SetPriorityNil sets the value for Priority to be an explicit nil
func (o *Task) SetPriorityNil() {
	o.Priority.Set(nil)
}

// UnsetPriority ensures that no value is present for Priority, not even an explicit nil
func (o *Task) UnsetPriority() {
	o.Priority.Unset()
}

// GetProgressMinutes returns the ProgressMinutes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Task) GetProgressMinutes() int32 {
	if o == nil || IsNil(o.ProgressMinutes.Get()) {
		var ret int32
		return ret
	}
	return *o.ProgressMinutes.Get()
}

// GetProgressMinutesOk returns a tuple with the ProgressMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Task) GetProgressMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProgressMinutes.Get(), o.ProgressMinutes.IsSet()
}

// HasProgressMinutes returns a boolean if a field has been set.
func (o *Task) HasProgressMinutes() bool {
	if o != nil && o.ProgressMinutes.IsSet() {
		return true
	}

	return false
}

// SetProgressMinutes gets a reference to the given NullableInt32 and assigns it to the ProgressMinutes field.
func (o *Task) SetProgressMinutes(v int32) {
	o.ProgressMinutes.Set(&v)
}

// SetProgressMinutesNil sets the value for ProgressMinutes to be an explicit nil
func (o *Task) SetProgressMinutesNil() {
	o.ProgressMinutes.Set(nil)
}

// UnsetProgressMinutes ensures that no value is present for ProgressMinutes, not even an explicit nil
func (o *Task) UnsetProgressMinutes() {
	o.ProgressMinutes.Unset()
}

// GetSchedulingHoursId returns the SchedulingHoursId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Task) GetSchedulingHoursId() string {
	if o == nil || IsNil(o.SchedulingHoursId.Get()) {
		var ret string
		return ret
	}
	return *o.SchedulingHoursId.Get()
}

// GetSchedulingHoursIdOk returns a tuple with the SchedulingHoursId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Task) GetSchedulingHoursIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SchedulingHoursId.Get(), o.SchedulingHoursId.IsSet()
}

// HasSchedulingHoursId returns a boolean if a field has been set.
func (o *Task) HasSchedulingHoursId() bool {
	if o != nil && o.SchedulingHoursId.IsSet() {
		return true
	}

	return false
}

// SetSchedulingHoursId gets a reference to the given NullableString and assigns it to the SchedulingHoursId field.
func (o *Task) SetSchedulingHoursId(v string) {
	o.SchedulingHoursId.Set(&v)
}

// SetSchedulingHoursIdNil sets the value for SchedulingHoursId to be an explicit nil
func (o *Task) SetSchedulingHoursIdNil() {
	o.SchedulingHoursId.Set(nil)
}

// UnsetSchedulingHoursId ensures that no value is present for SchedulingHoursId, not even an explicit nil
func (o *Task) UnsetSchedulingHoursId() {
	o.SchedulingHoursId.Unset()
}

// GetStartDateTime returns the StartDateTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Task) GetStartDateTime() string {
	if o == nil || IsNil(o.StartDateTime.Get()) {
		var ret string
		return ret
	}
	return *o.StartDateTime.Get()
}

// GetStartDateTimeOk returns a tuple with the StartDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Task) GetStartDateTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDateTime.Get(), o.StartDateTime.IsSet()
}

// HasStartDateTime returns a boolean if a field has been set.
func (o *Task) HasStartDateTime() bool {
	if o != nil && o.StartDateTime.IsSet() {
		return true
	}

	return false
}

// SetStartDateTime gets a reference to the given NullableString and assigns it to the StartDateTime field.
func (o *Task) SetStartDateTime(v string) {
	o.StartDateTime.Set(&v)
}

// SetStartDateTimeNil sets the value for StartDateTime to be an explicit nil
func (o *Task) SetStartDateTimeNil() {
	o.StartDateTime.Set(nil)
}

// UnsetStartDateTime ensures that no value is present for StartDateTime, not even an explicit nil
func (o *Task) UnsetStartDateTime() {
	o.StartDateTime.Unset()
}

func (o Task) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Task) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedItem, errItem := json.Marshal(o.Item)
	if errItem != nil {
		return map[string]interface{}{}, errItem
	}
	errItem = json.Unmarshal([]byte(serializedItem), &toSerialize)
	if errItem != nil {
		return map[string]interface{}{}, errItem
	}
	if o.BlockedByIds != nil {
		toSerialize["blockedByIds"] = o.BlockedByIds
	}
	if o.BlocksIds != nil {
		toSerialize["blocksIds"] = o.BlocksIds
	}
	if o.CanBeStartedAt.IsSet() {
		toSerialize["canBeStartedAt"] = o.CanBeStartedAt.Get()
	}
	if !IsNil(o.Completed) {
		toSerialize["completed"] = o.Completed
	}
	if o.DueDateTime.IsSet() {
		toSerialize["dueDateTime"] = o.DueDateTime.Get()
	}
	if o.DurationMinutes.IsSet() {
		toSerialize["durationMinutes"] = o.DurationMinutes.Get()
	}
	if o.EndDateTime.IsSet() {
		toSerialize["endDateTime"] = o.EndDateTime.Get()
	}
	if o.IsAutoIgnored.IsSet() {
		toSerialize["isAutoIgnored"] = o.IsAutoIgnored.Get()
	}
	if o.IsAutoScheduled.IsSet() {
		toSerialize["isAutoScheduled"] = o.IsAutoScheduled.Get()
	}
	if o.ListId.IsSet() {
		toSerialize["listId"] = o.ListId.Get()
	}
	if o.MinLengthMinutes.IsSet() {
		toSerialize["minLengthMinutes"] = o.MinLengthMinutes.Get()
	}
	if o.Priority.IsSet() {
		toSerialize["priority"] = o.Priority.Get()
	}
	if o.ProgressMinutes.IsSet() {
		toSerialize["progressMinutes"] = o.ProgressMinutes.Get()
	}
	if o.SchedulingHoursId.IsSet() {
		toSerialize["schedulingHoursId"] = o.SchedulingHoursId.Get()
	}
	if o.StartDateTime.IsSet() {
		toSerialize["startDateTime"] = o.StartDateTime.Get()
	}
	return toSerialize, nil
}

func (o *Task) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"itemType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTask := _Task{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTask)

	if err != nil {
		return err
	}

	*o = Task(varTask)

	return err
}

type NullableTask struct {
	value *Task
	isSet bool
}

func (v NullableTask) Get() *Task {
	return v.value
}

func (v *NullableTask) Set(val *Task) {
	v.value = val
	v.isSet = true
}

func (v NullableTask) IsSet() bool {
	return v.isSet
}

func (v *NullableTask) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTask(val *Task) *NullableTask {
	return &NullableTask{value: val, isSet: true}
}

func (v NullableTask) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTask) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
